const  a = 4;
const  b = 2;
console.log('a: ',a);
console.log('b: ',b); 
const  a = 4;
const  b = 2;
console.log('a: ',a);
console.log('b: ',b);
let c = 2;
console.log('a - b = ', c);
let e = 6;
console.log('a + b = ', e);
console.log('a / b = ', c);
let g = 8;
console.log('a * b = ', g);